### PR TITLE
Expose axios instance to enable customisation

### PR DESCRIPTION
**Pull request by skrabacz-michal**
Extend XAPI config with possibility to pass custom axios instance.

### CODE REVIEW

**Comment by CookieCookson** [comment]
Hello @skrabacz-michal and thank you for your contribution.

I'd love to understand your use case for passing in a custom axios instance. Are you looking to have more control over authentication, request transformation, axios version or something completely different?

**Comment by skrabacz-michal** [comment]
Hi @CookieCookson that is exactly the point - to have more control and in some cases reuse already preconfigured axios instance (e.g. with refresh token interceptor)

**Comment by CookieCookson** [comment]
I'm slightly anxious about being able to completely replace the internal tested axios version because it could have some untested and undesired side effects if there are any breaking changes between versions.

Would you be able to achieve the same results if there was a public getter for returning the internal axios instance? I understand you wouldn't be able to use the same axios instance within your application but you should be able to add interceptors and make other configuration changes.

I'm open to seeing examples where other libraries have followed your pattern of providing a custom axios instance, I'd love to see how they have considered axios versions e.g. specifying peerDependencies versions or checking version at runtime etc.

**Comment by skrabacz-michal** [comment]
@CookieCookson yes - exposing the axios instance would do the work.

**Comment by skrabacz-michal** [comment]
@CookieCookson should I create PR or you will take care of it?

**Comment by skrabacz-michal** [comment]
@CookieCookson I changed the code to just expose the axios instance

**Comment by CookieCookson** [comment]
Hey @skrabacz-michal this looks great! I'll look to do a release tonight with these changes.

**Comment by skrabacz-michal** [comment]
@CookieCookson looking forward to it

**Pull request merged**
