### PR TITLE
Basic Auth Helper

### PR DESCRIPTION
**Pull request by vbhayden**
Added a small helper function to remove the `Buffer(...)` syntax on the Node side:

- `./src/helpers/toBasicAuth.ts`
- `./src/helpers/toBasicAuth.spec.ts`

The basic example could then go from
```
const endpoint = "https://my-lms.com/endpoint";
const username = process.env.LRS_USERNAME || "";
const password = process.env.LRS_PASSWORD || "";
const auth = `Basic ${Buffer.from(username + ":" + password, "binary").toString("base64")}`;
const xapi = new XAPI(endpoint, auth);
```

to
```
const endpoint = "https://my-lms.com/endpoint";
const username = process.env.LRS_USERNAME || "";
const password = process.env.LRS_PASSWORD || "";
const auth = XAPI.toBasicAuth(username, password);
const xapi = new XAPI(endpoint, auth);
```

This uses the simple `btoa` NPM module, but I can remove that to keep the project clean if needed.

### CODE REVIEW

**Comment by CookieCookson** [comment]
Hi @vbhayden thanks for the PR!

I agree that the base64 method for node environments is pretty nasty looking. I do want to keep the dependencies on this project to a minimum, but this helper will not work in node based environments without the polyfill bundled.

I wonder if there is something that can be done with the Rollup config to only bundle the polyfill for the CJS export only, negating the need to import `btoa` in your helper.

**Comment by vbhayden** [comment]
Removed `btoa` 👋 

Not familiar this kind of setup, but will look around for a solution to the polyfill bit later tonight.

**Comment by CookieCookson** [comment]
No problem, I'll have a little look and see what can be done too.

**Comment by CookieCookson** [comment]
@vbhayden I've created a PR to your PR with a suggestion on how we can make this work :) https://github.com/vbhayden/xapi/pull/1

**Comment by vbhayden** [comment]
Resolved the package / locks to your updated one that used version 1 lockfiles.

**Comment by vbhayden** [comment]
had to google "LGTM", read as `Let's Get This Money`

**Comment by CookieCookson** [comment]
I wasn't planning any heists. 😆 

This is now released in `1.2.0` and has relevant documentation located at https://www.xapijs.dev/xapi-wrapper-library/helpers

**Pull request merged**
