### PR TITLE
accepts endpoint with or without trailing slash

### PR DESCRIPTION
**Pull request by beatthat**
- improvement: adds tests for endpoint resource urls
 - improvement: establishes setup for tests that don't rely on real/external xapi server

### CODE REVIEW

**Review by CookieCookson — APPROVED** [review]

**Comment by CookieCookson** [comment]
Looks great! Thanks for the additional work to start testing the library without testing against real systems. Have you got any ideas how we can retain those tests and when they should be run, but only when necessary? I'm thinking mock tests for PRs etc and then running the real tests during merges to master from a development branch or something similar.

**Comment by beatthat** [comment]
> Looks great! Thanks for the additional work to start testing the library without testing against real systems. Have you got any ideas how we can retain those tests and when they should be run, but only when necessary? I'm thinking mock tests for PRs etc and then running the real tests during merges to master from a development branch or something similar.

Should be harmless to keep the mocked tests and let them always run because very fast?

Would it be better if they just lived in a separate spec file (so easier to run either just the mocked tests or just the e2e tests by specifying jest args)?

**Comment by CookieCookson** [comment]
Agreed. Are you happy to amend your PR with these proposed changes?

To clarify:
- [ ] split tests into mock/e2e spec files
- [ ] mock tests to run on pushes to master and pull requests to master
- [ ] e2e tests to run on pushes to master

**Comment by beatthat** [comment]
I can make the changes. Are you sure you want mock tests to run only on push to master? Isn't that too late (i.e. problems should get caught before merge)?

**Comment by CookieCookson** [comment]
I would like the mock tests to run on both pushes to master and all pull requests please :) (just the e2e tests to only run on pushes to master)

**Comment by beatthat** [comment]
ok will make those changes

**Comment by beatthat** [comment]
I broke actions into two files one for pr and one for push to master. Let me know if works for you that way. I guess the alternative would be to have an action like `tests` that does everything except e2e tests and runs on both pr and push to master, and then a separate action `tests-e2e` that includes only the e2e tests etc.

**Review by CookieCookson — APPROVED** [review]

**Comment by CookieCookson** [comment]
A much better and needed improvement! Thank for all the great work.

**Pull request merged**
